import "dotenv/config";
import pg from "pg";

/* Faz 5.0: SQLite (node:sqlite) → PostgreSQL geçişi. Veri modeli/davranış birebir korunur;
   yalnız taban değişir. Bağlantı DATABASE_URL env değişkeninden (bkz. .env.example). */
const connectionString = process.env.DATABASE_URL;
if (!connectionString) throw new Error("DATABASE_URL tanımlı değil (bkz. .env.example)");

const pool = new pg.Pool({ connectionString });

/* pg tarafında double precision/integer → JS number; ama pg büyük sayı tiplerini bazen string
   döndürür. Bu şemada para/oran double precision, id integer — hepsi güvenle number'a sığar,
   yine de int8/numeric ileride girerse diye parser'ı number'a sabitliyoruz. */
pg.types.setTypeParser(pg.types.builtins.INT8, (v) => (v == null ? v : Number(v)));
pg.types.setTypeParser(pg.types.builtins.NUMERIC, (v) => (v == null ? v : Number(v)));

/* Eski SQLite kodu `?` yer tutucu kullanıyordu; Postgres `$1,$2…` ister. Çağrı yerlerini
   olduğu gibi bırakabilmek için `?`'leri sırayla $n'e çeviriyoruz (SQL'lerde başka `?` yok). */
function toPg(sql: string): string {
  let i = 0;
  return sql.replace(/\?/g, () => `$${++i}`);
}

export type RunResult = { id?: number; changes: number };

/** Küçük async db yüzeyi — eski `db.prepare(sql).all/get/run(...)` yerine `db.all/get/run(sql, ...params)`. */
export const db = {
  all: async <T = any>(sql: string, ...params: unknown[]): Promise<T[]> =>
    (await pool.query(toPg(sql), params)).rows as T[],
  get: async <T = any>(sql: string, ...params: unknown[]): Promise<T | undefined> =>
    (await pool.query(toPg(sql), params)).rows[0] as T | undefined,
  /** INSERT/UPDATE/DELETE. INSERT'e `RETURNING id` eklersen dönen `id`'yi verir (lastInsertRowid yerine). */
  run: async (sql: string, ...params: unknown[]): Promise<RunResult> => {
    const r = await pool.query(toPg(sql), params);
    return { id: (r.rows[0] as { id?: number } | undefined)?.id, changes: r.rowCount ?? 0 };
  },
  /** Tek bağlantıda BEGIN/COMMIT (havuzda farklı bağlantılara düşmesin diye) — atomik yan etkiler için. */
  tx: async <T>(fn: (t: TxClient) => Promise<T>): Promise<T> => {
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      const t: TxClient = {
        run: async (sql, ...params) => {
          const r = await client.query(toPg(sql), params);
          return { id: (r.rows[0] as { id?: number } | undefined)?.id, changes: r.rowCount ?? 0 };
        },
        get: async (sql, ...params) => (await client.query(toPg(sql), params)).rows[0],
      };
      const out = await fn(t);
      await client.query("COMMIT");
      return out;
    } catch (e) {
      await client.query("ROLLBACK");
      throw e;
    } finally {
      client.release();
    }
  },
};

export type TxClient = {
  run: (sql: string, ...params: unknown[]) => Promise<RunResult>;
  get: <T = any>(sql: string, ...params: unknown[]) => Promise<T | undefined>;
};

/* SQLite'ın datetime('now','localtime') / date('now','localtime') fonksiyonlarının yerine
   sunucu yerel saatini JS'te üretip parametre olarak geçiriyoruz (lehçe bağımsız + TZ net).
   Biçim SQLite ile birebir: 'YYYY-MM-DD HH:MM:SS' ve 'YYYY-MM-DD'. */
const pad = (n: number) => String(n).padStart(2, "0");
export function nowLocal(): string {
  const d = new Date();
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
}
export function todayLocal(): string {
  const d = new Date();
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}

/* Faz 5.2 — çok-kiracılık: bu tablolar kullanıcıya özeldir (user_id ile scope'lanır).
   prices/price_history GLOBAL (piyasa verisi, herkes için aynı); settings global (fx/tefas),
   kullanıcı ayarları (horizon/cash_funds) user_settings'te. */
export const TENANT_TABLES = [
  "accounts", "recurring", "loans", "oneoffs", "trades", "cards", "card_txs", "categories", "transactions",
] as const;
/** settings tablosunda GLOBAL kalan anahtarlar (piyasa verisi); gerisi kullanıcıya özel (user_settings). */
export const GLOBAL_SETTING_KEYS = new Set(["fx_usd_try", "tefas_last_fetch"]);

/* Şema — Postgres lehçesi. SQLite karşılığıyla birebir:
   INTEGER PK AUTOINCREMENT → integer GENERATED BY DEFAULT AS IDENTITY (taşımada açık id yazılabilsin),
   REAL → double precision (SQLite REAL = 8 bayt float; Postgres double precision de öyle — para hassasiyeti korunur),
   TEXT → text. CHECK/FK/ON CONFLICT deseni Postgres'te aynen çalışır. */
export async function initDb(): Promise<void> {
  await pool.query(`
CREATE TABLE IF NOT EXISTS accounts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  balance double precision NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS recurring (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind text NOT NULL CHECK (kind IN ('income','expense')),
  name text NOT NULL,
  amount double precision NOT NULL,
  day integer NOT NULL CHECK (day BETWEEN 1 AND 31),
  from_month text,
  to_month text
);
CREATE TABLE IF NOT EXISTS loans (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  amount double precision NOT NULL,
  first_date text NOT NULL,
  total integer NOT NULL
);
CREATE TABLE IF NOT EXISTS oneoffs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date text NOT NULL,
  name text NOT NULL,
  amount double precision NOT NULL
);
CREATE TABLE IF NOT EXISTS trades (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date text NOT NULL,
  asset_type text NOT NULL CHECK (asset_type IN ('BIST','FON','ALTIN','DOVIZ','KRIPTO','ETF')),
  symbol text NOT NULL,
  side text NOT NULL CHECK (side IN ('ALIŞ','SATIŞ')),
  qty double precision NOT NULL,
  price double precision NOT NULL,
  fee double precision NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'TRY'
);
CREATE TABLE IF NOT EXISTS prices (
  symbol text NOT NULL,
  asset_type text NOT NULL,
  price double precision NOT NULL,
  source text NOT NULL DEFAULT 'manual',
  updated_at text NOT NULL,
  currency text NOT NULL DEFAULT 'TRY',
  PRIMARY KEY (symbol, asset_type)
);
CREATE TABLE IF NOT EXISTS cards (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  limit_amount double precision NOT NULL DEFAULT 0,
  statement_day integer NOT NULL CHECK (statement_day BETWEEN 1 AND 31),
  due_day integer NOT NULL CHECK (due_day BETWEEN 1 AND 31)
);
CREATE TABLE IF NOT EXISTS card_txs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id integer NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  date text NOT NULL,
  name text NOT NULL,
  amount double precision NOT NULL,
  installments integer NOT NULL DEFAULT 1 CHECK (installments >= 1)
);
CREATE TABLE IF NOT EXISTS settings (
  key text PRIMARY KEY,
  value text NOT NULL
);
CREATE TABLE IF NOT EXISTS categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  kind text NOT NULL CHECK (kind IN ('income','expense')),
  color text
);
CREATE TABLE IF NOT EXISTS transactions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date text NOT NULL,
  name text NOT NULL,
  amount double precision NOT NULL,
  category_id integer REFERENCES categories(id) ON DELETE SET NULL,
  account_id integer REFERENCES accounts(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS price_history (
  symbol text NOT NULL,
  asset_type text NOT NULL,
  date text NOT NULL,
  price double precision NOT NULL,
  currency text NOT NULL DEFAULT 'TRY',
  PRIMARY KEY (symbol, asset_type, date)
);
/* Faz 5.1 — auth. users: kayıtlı kullanıcı; sessions: server-side oturum (revoke edilebilir).
   Çok-kiracılık (user_id scoping) Faz 5.2'de gelir; şimdilik veri paylaşımlı, kayıt yalnız ilk owner'a açık. */
CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  created_at text NOT NULL
);
CREATE TABLE IF NOT EXISTS sessions (
  token text PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at text NOT NULL,
  expires_at text NOT NULL
);
`);

  /* Faz 5.2 — çok-kiracılık: tenant tablolarına user_id (mevcut DB'lere ALTER ile eklenir; fresh'te de
     zararsız). users bu noktada kesin var (yukarıda oluşturuldu). prices/price_history GLOBAL kalır. */
  await pool.query(`
${TENANT_TABLES.map((t) => `ALTER TABLE ${t} ADD COLUMN IF NOT EXISTS user_id integer REFERENCES users(id) ON DELETE CASCADE;`).join("\n")}
CREATE TABLE IF NOT EXISTS user_settings (
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  key text NOT NULL,
  value text NOT NULL,
  PRIMARY KEY (user_id, key)
);
-- elle girilen fiyat override'ları KULLANICIYA ÖZEL (global prices = otomatik/piyasa; kullanıcının eli global'i etkilemez)
CREATE TABLE IF NOT EXISTS user_prices (
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  symbol text NOT NULL,
  asset_type text NOT NULL,
  price double precision NOT NULL,
  updated_at text NOT NULL,
  currency text NOT NULL DEFAULT 'TRY',
  PRIMARY KEY (user_id, symbol, asset_type)
);
-- kategori adı artık KULLANICI BAŞINA benzersiz (eski global UNIQUE düşürülür)
ALTER TABLE categories DROP CONSTRAINT IF EXISTS categories_name_key;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'categories_user_name_key') THEN
    ALTER TABLE categories ADD CONSTRAINT categories_user_name_key UNIQUE (user_id, name);
  END IF;
END $$;
`);
}
