/* ————— TOPLU İÇE AKTARMA YAZIMI (Faz 45.3) —————
   Ekstre içe aktarmanın iki ucu (`POST /transactions/bulk`, `POST /cardtxs/bulk`) satırları
   buradan yazar. Rotalar index.ts'te kalır (asistan rota kapısı yalnız orayı tarar); burada
   yalnız SQL var — ayrı dosyada olması, gerçek veritabanına karşı geri alınan bir transaction
   içinde doğrudan sınanabilsin diye.

   SABİT SAYIDA SORGU, satır sayısından bağımsız. Eskiden her satır için iki sorgu atılıyordu
   (işlem INSERT … RETURNING id, sonra hesap hareketi): iki yıllık 735 satırlık bir döküm ≈1.470
   gidiş-dönüştü. Sebep iş mantığı değildi — hareket işlemin kimliğini `source_id` olarak taşımak
   zorunda ve kod tekli ucun `applyEntry`sini satır satır çağırıyordu. Kimlikler önden ayrılınca
   (`nextval`) iki tablo da tek INSERT'le yazılır. Diziler `unnest` ile TEK parametre olarak
   geçer, yani Postgres'in 65.535 parametre sınırı satır sayısını kısıtlamaz.

   Sözleşme `applyEntry` ile aynıdır: hesabı ya da hareket zarfı olmayan satır deftere girmez. */

import { nowLocal, type TxClient } from "./db.js";

export type TopluIslem = { date: string; enc: string; entry_enc: string | null; category_id: number | null; account_id: number | null };
export type TopluKart = { card_id: number; date: string; enc: string; category_id: number | null };

/** Tabloya N kimlik ayırır. Kimlik kolonları `GENERATED BY DEFAULT AS IDENTITY` olduğundan
    açık değer kabul edilir; `nextval` diziden aldığı için sonraki normal INSERT'lerle çakışmaz. */
async function kimlikAyir(t: TxClient, tablo: "transactions", n: number): Promise<number[]> {
  const r = await t.all<{ id: number }>(
    `SELECT nextval(pg_get_serial_sequence('${tablo}', 'id'))::int AS id FROM generate_series(1, ?::int)`, n,
  );
  return r.map((x) => x.id);
}

/** Gerçekleşen işlemler + hesaba bağlı olanların hareketleri: 3 sorgu. Eklenen kimlikleri döndürür. */
export async function topluIslemYaz(t: TxClient, uid: number, rows: TopluIslem[]): Promise<number[]> {
  if (rows.length === 0) return [];
  const ids = await kimlikAyir(t, "transactions", rows.length);
  await t.run(
    `INSERT INTO transactions (id, date, enc, category_id, account_id, user_id)
     SELECT id, date, enc, category_id, account_id, ?::int
     FROM unnest(?::int[], ?::text[], ?::text[], ?::int[], ?::int[]) AS u(id, date, enc, category_id, account_id)`,
    uid, ids, rows.map((r) => r.date), rows.map((r) => r.enc), rows.map((r) => r.category_id), rows.map((r) => r.account_id),
  );
  const hareket = rows.map((r, i) => ({ ...r, id: ids[i] })).filter((r) => r.account_id != null && r.entry_enc);
  if (hareket.length) {
    await t.run(
      `INSERT INTO account_entries (account_id, date, kind, source_table, source_id, enc, created_at, user_id)
       SELECT account_id, date, 'islem', 'transactions', source_id, enc, ?, ?::int
       FROM unnest(?::int[], ?::text[], ?::int[], ?::text[]) AS u(account_id, date, source_id, enc)`,
      nowLocal(), uid, hareket.map((r) => r.account_id), hareket.map((r) => r.date), hareket.map((r) => r.id), hareket.map((r) => r.entry_enc),
    );
  }
  return ids;
}

/** Kart harcamaları: bakiye yan etkisi yok, tek sorgu. */
export async function topluKartYaz(t: TxClient, uid: number, rows: TopluKart[]): Promise<void> {
  if (rows.length === 0) return;
  await t.run(
    `INSERT INTO card_txs (card_id, date, enc, category_id, user_id)
     SELECT card_id, date, enc, category_id, ?::int
     FROM unnest(?::int[], ?::text[], ?::text[], ?::int[]) AS u(card_id, date, enc, category_id)`,
    uid, rows.map((r) => r.card_id), rows.map((r) => r.date), rows.map((r) => r.enc), rows.map((r) => r.category_id),
  );
}

/** Faz 45.7 — "geçmişi de ekle, açılışı geri çek": dökümün açılıştan ÖNCEKİ satırları eklenirken
    hesabın açılış hareketi aynı transaction'da eskiye alınır ve tutarı eklenen satırların toplamı
    kadar azaltılır (tutarı istemci hesaplar — zarflı). Bugünkü bakiye DEĞİŞMEZ, açılış gününden
    sonraki her günün bakiyesi değişmez; geçmiş deftere girer. Ayrı bir istek olsaydı biri yazılıp
    diğeri kalınca bakiye şişik kalırdı. En eski açılış hareketi güncellenir; yoksa false. */
export async function acilisGuncelle(t: TxClient, uid: number, accountId: number, date: string, enc: string): Promise<boolean> {
  const r = await t.run(
    `UPDATE account_entries SET date=?, enc=? WHERE id = (
       SELECT id FROM account_entries WHERE account_id=? AND user_id=? AND kind='acilis' ORDER BY date, id LIMIT 1
     ) AND user_id=?`,
    date, enc, accountId, uid, uid,
  );
  return r.changes > 0;
}
